### ISSUE TITLE
数据多少条？能否购买或共享？

### ISSUE THREAD

**Issue by hechengyuan** [yanweijia/foodsSpider#1]
您好，我是医科大学的学生，想获取尽量完善的食物数据来做数据分析，您爬取的薄荷网的数据有多少条，能否卖或者共享给我？

**Comment by yanweijia** [comment]
暂时只爬取了每个分类的前一百个,可以看我 repo 中的 slimming_android, 直接下载应该可以使用,目前内容就这些,可以直接共享给你. 也可以自己运行程序获取数据, 需要更多数据暂时还没思路

**Comment by hechengyuan** [comment]
前一百个有点少，我这边也就只能爬前100，我在想找一个list，去请求他们的搜索，再爬出来数据

**Comment by yanweijia** [comment]
薄荷网数据有一部分是网友上传,剩余部分来自于 [中国食物成分表](http://ccftp.scu.edu.cn/Download/8250e177-16de-423c-a184-9a003a0b56c7.pdf),如若没有更好的渠道可以尝试去寻找此书籍的电子版,然后想办法导出数据.

**Comment by yanweijia** [comment]
刚才在 github 搜索了一下,有类似项目, git repo 里面有已经爬虫好的数据可以直接使用 ,  里面中文使用的 unicode 编码,可以找个在线转换的网站进行转换. 
项目地址:[seawaylee/boohee_spider](https://github.com/seawaylee/boohee_spider)
文件直达地址: [薄荷官方所有食物共2807个.json](https://github.com/seawaylee/boohee_spider/blob/master/%E8%96%84%E8%8D%B7%E5%AE%98%E6%96%B9%E6%89%80%E6%9C%89%E9%A3%9F%E7%89%A9%E5%85%B12807%E4%B8%AA.json)

**Comment by yanweijia** [comment]
另外,还找到一条excel 总结的数据 [《中国食物成分表》2015 excel版](http://blog.too2.net/?p=374)
文件: 
[中国食物成分表2015.xls.zip](https://github.com/yanweijia/foodsSpider/files/2042704/2015.xls.zip)
